package main

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// header marks the file as generated. Tools look for this exact form, and the writer refuses to overwrite a file
// that does not carry it, so a mistyped -out cannot eat a source file.
const header = "// Code generated by monqgen. DO NOT EDIT."

// reserved are the members a generated array type already has. An element field whose Go name is one of these would
// be shadowed by the array's own, so generation stops instead of quietly producing paths that resolve elsewhere.
var reserved = map[string]string{
	"Path":       "the array's own path",
	"At":         "the element at an index",
	"Positional": "the element a query matched",
	"All":        "every element",
	"Filtered":   "the elements an array filter picks",
}

// Generate renders the path tree as Go source for the given package.
//
// Names are worked out first, in one pass over the tree, so that the type declarations and the values built from
// them agree. Rendering then reads those names rather than deriving them a second time.
//
// The value the paths land in is named by varName, or by the model with Paths appended when varName is empty. Only
// the value takes that name: the types are the generator's own business and go on being named after the model, so
// renaming the value cannot rename anything a caller reads.
func Generate(model *Struct, pkgName, varName string) ([]byte, error) {
	if varName == "" {
		varName = model.Name + "Paths"
	}

	g := &generator{names: map[string]bool{}}

	plan := g.plan(model, model.Name, "")
	if err := plan.check(); err != nil {
		return nil, err
	}

	if g.names[varName] {
		return nil, fmt.Errorf("the value cannot be named %s: a generated type already has that name", varName)
	}

	var buf bytes.Buffer

	fmt.Fprintf(&buf, "%s\n\npackage %s\n\nimport \"github.com/behzadsh/monq\"\n", header, pkgName)
	buf.WriteString(plan.declarations())
	fmt.Fprintf(
		&buf, "\n// %s holds the document paths of %s.\nvar %s = %s\n",
		varName, model.Name, varName, plan.literal(),
	)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("formatting generated source: %w", err)
	}

	return src, nil
}

// generator hands out type names, keeping track of the ones already taken.
type generator struct {
	names map[string]bool
}

// document is one struct in the tree with the name its generated type will have.
type document struct {
	typeName string
	name     string
	fields   []field
}

// field is one member of a generated struct, with everything rendering needs already decided.
type field struct {
	goName string
	path   string
	kind   Kind
	stops  bool

	// child is the document a field descends into, whether nested directly or held in an array.
	child *document

	// wrapper is the type carrying an array's own path and its positional methods, empty unless the field is an
	// array of documents.
	wrapper string
}

// plan walks the parsed tree and settles every generated name, with base accumulating the Go field names leading
// here and prefix the document path.
func (g *generator) plan(s *Struct, base, prefix string) *document {
	doc := &document{typeName: g.typeName(base), name: s.Name}

	for _, f := range s.Fields {
		out := field{goName: f.GoName, path: join(prefix, f.Key), kind: f.Kind, stops: f.Elem == nil}

		if f.Elem != nil {
			out.child = g.plan(f.Elem, base+f.GoName, out.path)
			if f.Kind == KindArray {
				out.wrapper = out.child.typeName + "Array"
			}
		}

		doc.fields = append(doc.fields, out)
	}

	return doc
}

// typeName reserves a name for a generated type, adding a number if that name is already taken.
//
// The name is the one the value would have with an underscore in front of it, _UserPaths beside UserPaths. That
// keeps the type out of the way of the value, which is the name callers write, and out of the way of an
// unexported model, whose value would otherwise want the same identifier the root type does.
func (g *generator) typeName(base string) string {
	name := "_" + base + "Paths"
	if !g.names[name] {
		g.names[name] = true

		return name
	}

	for i := 2; ; i++ {
		candidate := name + strconv.Itoa(i)
		if !g.names[candidate] {
			g.names[candidate] = true

			return candidate
		}
	}
}

// check stops generation when an element field would be shadowed by a member its array type already has.
func (d *document) check() error {
	for _, f := range d.fields {
		if f.child == nil {
			continue
		}

		if f.kind == KindArray {
			for _, elem := range f.child.fields {
				if what, taken := reserved[elem.goName]; taken {
					return fmt.Errorf(
						"field %s.%s cannot be generated: an array of documents already uses %s for %s; rename the Go field",
						f.child.name, elem.goName, elem.goName, what,
					)
				}
			}
		}

		if err := f.child.check(); err != nil {
			return err
		}
	}

	return nil
}

// declarations writes this document's struct type, preceded by the types of everything nested inside it.
func (d *document) declarations() string {
	var nested, fields strings.Builder

	for _, f := range d.fields {
		switch {
		case f.kind == KindArray && f.child != nil:
			nested.WriteString(f.child.declarations())
			nested.WriteString("\n" + f.child.constructor() + "\n")
			nested.WriteString("\n" + f.arrayType() + "\n")
			fmt.Fprintf(&fields, "\t%s %s\n", f.goName, f.wrapper)
		case f.kind == KindArray:
			fmt.Fprintf(&fields, "\t%s monq.ArrayPath\n", f.goName)
		case f.kind == KindDocument && f.child != nil:
			nested.WriteString(f.child.declarations())
			fmt.Fprintf(&fields, "\t%s %s\n", f.goName, f.child.typeName)
		case f.kind == KindDocument:
			fmt.Fprintf(&fields, "\t// %s repeats a type named further up, so the paths stop here.\n", f.goName)
			fmt.Fprintf(&fields, "\t%s monq.FieldPath\n", f.goName)
		case f.kind == KindMap:
			fmt.Fprintf(
				&fields, "\t// %s has keys that are not known ahead of time, so nothing below it is named.\n",
				f.goName,
			)
			fmt.Fprintf(&fields, "\t%s monq.FieldPath\n", f.goName)
		default:
			fmt.Fprintf(&fields, "\t%s monq.FieldPath\n", f.goName)
		}
	}

	return nested.String() + fmt.Sprintf("\ntype %s struct {\n%s}\n", d.typeName, fields.String())
}

// literal writes the value of this document, with every path already resolved.
func (d *document) literal() string {
	var b strings.Builder

	fmt.Fprintf(&b, "%s{\n", d.typeName)

	for _, f := range d.fields {
		switch {
		case f.kind == KindArray && f.child != nil:
			fmt.Fprintf(
				&b, "\t%s: %s{Path: %q, %s: %s(%q)},\n",
				f.goName, f.wrapper, f.path, f.child.typeName, ctor(f.child.typeName), f.path,
			)
		case f.kind == KindArray:
			fmt.Fprintf(&b, "\t%s: monq.ArrayPath{Path: %q},\n", f.goName, f.path)
		case f.kind == KindDocument && f.child != nil:
			fmt.Fprintf(&b, "\t%s: %s,\n", f.goName, f.child.literal())
		default:
			fmt.Fprintf(&b, "\t%s: %q,\n", f.goName, f.path)
		}
	}

	b.WriteString("}")

	return b.String()
}

// constructor writes the function that builds this document's paths under a prefix, which is what lets an array's
// positional methods put an index or a "$" in front of them.
func (d *document) constructor() string {
	var b strings.Builder

	fmt.Fprintf(&b, "// %s returns the paths of one element under prefix.\n", ctor(d.typeName))
	fmt.Fprintf(&b, "func %s(prefix string) %s {\n\treturn %s{\n", ctor(d.typeName), d.typeName, d.typeName)

	for _, f := range d.fields {
		key := f.path[strings.LastIndex(f.path, ".")+1:]

		switch {
		case f.kind == KindArray && f.child == nil:
			fmt.Fprintf(&b, "\t\t%s: monq.ArrayPath{Path: monq.FieldPath(prefix + %q)},\n", f.goName, "."+key)
		case f.child != nil:
			fmt.Fprintf(&b, "\t\t%s: %s(prefix + %q),\n", f.goName, ctor(f.child.typeName), "."+key)
		default:
			fmt.Fprintf(&b, "\t\t%s: monq.FieldPath(prefix + %q),\n", f.goName, "."+key)
		}
	}

	b.WriteString("\t}\n}")

	return b.String()
}

// arrayType writes the wrapper carrying an array's own path, the dotted paths of its elements, and the four ways
// of naming a position inside it.
func (f field) arrayType() string {
	var b strings.Builder

	fmt.Fprintf(
		&b, "// %s is the %s array: its own path, the dotted paths of its elements, and the positional\n",
		f.wrapper, f.goName,
	)
	b.WriteString("// forms for naming particular elements.\n")
	fmt.Fprintf(&b, "type %s struct {\n\tPath monq.FieldPath\n\t%s\n}\n", f.wrapper, f.child.typeName)

	methods := []struct {
		name      string
		params    string
		arguments string
		doc       string
	}{
		{name: "At", params: "i int", arguments: "i", doc: "the element at index i"},
		{name: "Positional", doc: "the element a query matched"},
		{name: "All", doc: "every element"},
		{name: "Filtered", params: "identifier string", arguments: "identifier", doc: "the elements an array filter picks out"},
	}

	for _, m := range methods {
		fmt.Fprintf(
			&b, "\n// %s returns the paths of %s.\nfunc (a %s) %s(%s) %s {\n",
			m.name, m.doc, f.wrapper, m.name, m.params, f.child.typeName,
		)
		fmt.Fprintf(
			&b, "\treturn %s(string(monq.ArrayPath{Path: a.Path}.%s(%s)))\n}\n",
			ctor(f.child.typeName), m.name, m.arguments,
		)
	}

	return b.String()
}

// join puts one key after a prefix, taking the key alone at the root.
func join(prefix, key string) string {
	if prefix == "" {
		return key
	}

	return prefix + "." + key
}

// ctor names the function building a generated type's paths under a prefix.
//
// The underscore that keeps generated types out of the way of the values named after them has no place in a
// function name, so it comes off and the letter it hid is capitalised: _UserItemsPaths gives newUserItemsPaths.
func ctor(typeName string) string {
	name := strings.TrimPrefix(typeName, "_")
	if name == "" {
		return "new"
	}

	return "new" + strings.ToUpper(name[:1]) + name[1:]
}
