// Code generated by monqgen. DO NOT EDIT.

package main

import "github.com/behzadsh/monq"

type productRatingsPaths struct {
	User  monq.FieldPath
	Score monq.FieldPath
}

// newProductRatingsPaths returns the paths of one element under prefix.
func newProductRatingsPaths(prefix string) productRatingsPaths {
	return productRatingsPaths{
		User:  monq.FieldPath(prefix + ".user"),
		Score: monq.FieldPath(prefix + ".score"),
	}
}

// productRatingsPathsArray is the Ratings array: its own path, the dotted paths of its elements, and the positional
// forms for naming particular elements.
type productRatingsPathsArray struct {
	Path monq.FieldPath
	productRatingsPaths
}

// At returns the paths of the element at index i.
func (a productRatingsPathsArray) At(i int) productRatingsPaths {
	return newProductRatingsPaths(string(monq.ArrayPath{Path: a.Path}.At(i)))
}

// Positional returns the paths of the element a query matched.
func (a productRatingsPathsArray) Positional() productRatingsPaths {
	return newProductRatingsPaths(string(monq.ArrayPath{Path: a.Path}.Positional()))
}

// All returns the paths of every element.
func (a productRatingsPathsArray) All() productRatingsPaths {
	return newProductRatingsPaths(string(monq.ArrayPath{Path: a.Path}.All()))
}

// Filtered returns the paths of the elements an array filter picks out.
func (a productRatingsPathsArray) Filtered(identifier string) productRatingsPaths {
	return newProductRatingsPaths(string(monq.ArrayPath{Path: a.Path}.Filtered(identifier)))
}

type productWarehousePaths struct {
	Type        monq.FieldPath
	Coordinates monq.ArrayPath
}

type productPaths struct {
	ID        monq.FieldPath
	SKU       monq.FieldPath
	Name      monq.FieldPath
	Category  monq.FieldPath
	Price     monq.FieldPath
	Stock     monq.FieldPath
	Flags     monq.FieldPath
	Tags      monq.ArrayPath
	Ratings   productRatingsPathsArray
	Warehouse productWarehousePaths
	CreatedAt monq.FieldPath
}

// ProductPaths holds the document paths of Product.
var ProductPaths = productPaths{
	ID:       "_id",
	SKU:      "sku",
	Name:     "name",
	Category: "category",
	Price:    "price",
	Stock:    "stock",
	Flags:    "flags",
	Tags:     monq.ArrayPath{Path: "tags"},
	Ratings:  productRatingsPathsArray{Path: "ratings", productRatingsPaths: newProductRatingsPaths("ratings")},
	Warehouse: productWarehousePaths{
		Type:        "warehouse.type",
		Coordinates: monq.ArrayPath{Path: "warehouse.coordinates"},
	},
	CreatedAt: "created_at",
}
