// Code generated by monqgen. DO NOT EDIT.

package example

import "github.com/behzadsh/monq"

type _sessionDocDevicePaths struct {
	Platform monq.FieldPath
	Version  monq.FieldPath
}

type _sessionDocPaths struct {
	ID        monq.FieldPath
	UserID    monq.FieldPath
	Device    _sessionDocDevicePaths
	ExpiresAt monq.FieldPath
}

// sessionDocPaths holds the document paths of sessionDoc.
var sessionDocPaths = _sessionDocPaths{
	ID:     "_id",
	UserID: "user_id",
	Device: _sessionDocDevicePaths{
		Platform: "device.platform",
		Version:  "device.version",
	},
	ExpiresAt: "expires_at",
}
