// Code generated by monqgen. DO NOT EDIT.

package example

import "github.com/behzadsh/monq"

type _UserAddressPaths struct {
	Street monq.FieldPath
	City   monq.FieldPath
}

type _UserItemsPaths struct {
	SKU      monq.FieldPath
	Quantity monq.FieldPath
	Price    monq.FieldPath
}

// newUserItemsPaths returns the paths of one element under prefix.
func newUserItemsPaths(prefix string) _UserItemsPaths {
	return _UserItemsPaths{
		SKU:      monq.FieldPath(prefix + ".sku"),
		Quantity: monq.FieldPath(prefix + ".qty"),
		Price:    monq.FieldPath(prefix + ".price"),
	}
}

// _UserItemsPathsArray is the Items array: its own path, the dotted paths of its elements, and the positional
// forms for naming particular elements.
type _UserItemsPathsArray struct {
	Path monq.FieldPath
	_UserItemsPaths
}

// At returns the paths of the element at index i.
func (a _UserItemsPathsArray) At(i int) _UserItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.At(i)))
}

// Positional returns the paths of the element a query matched.
func (a _UserItemsPathsArray) Positional() _UserItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.Positional()))
}

// All returns the paths of every element.
func (a _UserItemsPathsArray) All() _UserItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.All()))
}

// Filtered returns the paths of the elements an array filter picks out.
func (a _UserItemsPathsArray) Filtered(identifier string) _UserItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.Filtered(identifier)))
}

type _UserPaths struct {
	ID        monq.FieldPath
	Email     monq.FieldPath
	Address   _UserAddressPaths
	Tags      monq.ArrayPath
	Items     _UserItemsPathsArray
	CreatedAt monq.FieldPath
}

// UserPaths holds the document paths of User.
var UserPaths = _UserPaths{
	ID:    "_id",
	Email: "email",
	Address: _UserAddressPaths{
		Street: "address.street",
		City:   "address.city",
	},
	Tags:      monq.ArrayPath{Path: "tags"},
	Items:     _UserItemsPathsArray{Path: "items", _UserItemsPaths: newUserItemsPaths("items")},
	CreatedAt: "created_at",
}
