// Code generated by monqgen. DO NOT EDIT.

package example

import "github.com/behzadsh/monq"

type userAddressPaths struct {
	Street monq.FieldPath
	City   monq.FieldPath
}

type userItemsPaths struct {
	SKU      monq.FieldPath
	Quantity monq.FieldPath
	Price    monq.FieldPath
}

// newUserItemsPaths returns the paths of one element under prefix.
func newUserItemsPaths(prefix string) userItemsPaths {
	return userItemsPaths{
		SKU:      monq.FieldPath(prefix + ".sku"),
		Quantity: monq.FieldPath(prefix + ".qty"),
		Price:    monq.FieldPath(prefix + ".price"),
	}
}

// userItemsPathsArray is the Items array: its own path, the dotted paths of its elements, and the positional
// forms for naming particular elements.
type userItemsPathsArray struct {
	Path monq.FieldPath
	userItemsPaths
}

// At returns the paths of the element at index i.
func (a userItemsPathsArray) At(i int) userItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.At(i)))
}

// Positional returns the paths of the element a query matched.
func (a userItemsPathsArray) Positional() userItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.Positional()))
}

// All returns the paths of every element.
func (a userItemsPathsArray) All() userItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.All()))
}

// Filtered returns the paths of the elements an array filter picks out.
func (a userItemsPathsArray) Filtered(identifier string) userItemsPaths {
	return newUserItemsPaths(string(monq.ArrayPath{Path: a.Path}.Filtered(identifier)))
}

type userPaths struct {
	ID        monq.FieldPath
	Email     monq.FieldPath
	Address   userAddressPaths
	Tags      monq.ArrayPath
	Items     userItemsPathsArray
	CreatedAt monq.FieldPath
}

// UserPaths holds the document paths of User.
var UserPaths = userPaths{
	ID:    "_id",
	Email: "email",
	Address: userAddressPaths{
		Street: "address.street",
		City:   "address.city",
	},
	Tags:      monq.ArrayPath{Path: "tags"},
	Items:     userItemsPathsArray{Path: "items", userItemsPaths: newUserItemsPaths("items")},
	CreatedAt: "created_at",
}
